modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Edibles"
logoFile="icon.png"

[[mods]]
modId="edibles"
version="4.3"
displayName="Edibles"
displayURL="https://serilum.com/mod/edibles"
authors="Rick South"
description='''Makes lots of ingredients edible, after which the player receives a short status effect.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, BirdieMiner, Cherriesaurus, Jack, Jeremy Langford, Michael W. S., pepe1191, Shana Gitnick, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.edibles]]
    modId="collective"
    mandatory=true
    versionRange="[7.55,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.edibles]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.6]"
    ordering="NONE"
    side="BOTH"
